// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmdoqbkodkzoswbzrlsw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZG9xYmtvZGt6b3N3YnpybHN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MjUyMDgsImV4cCI6MjA2MDIwMTIwOH0.1gvnn0Gz9oBHzT0tAA650HWM-TTGdUPYOL_ckfJ6K0g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);